version: "3"

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    env_file:
      - .env
  backend:
    build: .
    command: bash -c "dockerize -wait tcp://db:5432 && python3 manage.py migrate && pipenv install --system --dev && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/var/admin
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
